<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-F8GGD3E" failures="1" tests="3" name="Test" time="35.939" errors="0" timestamp="2021-12-14T23:13:12 IST">
  <testcase classname="project.TestSignUp" name="test_signUp" time="4.684">
    <failure type="java.lang.AssertionError" message="This user already exist. expected [Sign up successful.] but found [This user already exist.]">
      <![CDATA[java.lang.AssertionError: This user already exist. expected [Sign up successful.] but found [This user already exist.]
at project.TestSignUp.test_signUp(TestSignUp.java:76)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test_signUp -->
  <testcase classname="project.TestLogin" name="test_login" time="4.39"/>
  <testcase classname="project.TestOrderProducts" name="test_addToCart" time="18.221"/>
</testsuite> <!-- Test -->
