<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-F8GGD3E" failures="2" tests="8" name="Test" time="55.043" errors="0" timestamp="2021-12-15T14:02:21 IST">
  <testcase classname="project.TestSignUp" name="test_signUp" time="4.799">
    <failure type="java.lang.AssertionError" message="This user already exist. expected [Sign up successful.] but found [This user already exist.]">
      <![CDATA[java.lang.AssertionError: This user already exist. expected [Sign up successful.] but found [This user already exist.]
at project.TestSignUp.test_signUp(TestSignUp.java:95)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test_signUp -->
  <testcase classname="project.TestSignUp" name="test_signUp" time="4.593"/>
  <testcase classname="project.TestSignUp" name="test_signUp" time="4.635">
    <failure type="java.lang.AssertionError" message="This user already exist. expected [Sign up successful.] but found [This user already exist.]">
      <![CDATA[java.lang.AssertionError: This user already exist. expected [Sign up successful.] but found [This user already exist.]
at project.TestSignUp.test_signUp(TestSignUp.java:95)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test_signUp -->
  <testcase classname="project.TestSignUp" name="test_signUp" time="4.811"/>
  <testcase classname="project.TestLogin" name="test_login" time="4.271"/>
  <testcase classname="project.TestLogin" name="test_login" time="3.905"/>
  <testcase classname="project.TestLogin" name="test_login" time="3.92"/>
  <testcase classname="project.TestLogin" name="test_login" time="4.213"/>
</testsuite> <!-- Test -->
